# Generated by Django 2.0.4 on 2018-04-19 11:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
                ('type', models.IntegerField()),
                ('description', markdownx.models.MarkdownxField(help_text='Markdown Enabled')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=30)),
                ('content', markdownx.models.MarkdownxField(help_text='Markdown Enabled')),
                ('date_posted', models.DateField(default=datetime.date.today, verbose_name='Date Posted')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Category')),
            ],
        ),
    ]
